### ISSUE TITLE
How to format your Docker Compose file?

### ISSUE THREAD

**Issue by mpolinowski** [uchenic/compose-to-nomad#2]
Hi @uchenic,

thank for sharing this code - I have been looking for something like it for a while!

But I keep running into errors when I try to run conversions - e.g.:

```bash
Traceback (most recent call last):
  File "/usr/local/bin/nomadgen", line 7, in <module>
    main(args)
  File "/usr/local/lib/python3.9/dist-packages/composenomadconvertor/produce_tasks.py", line 104, in main
    compose_obj = l.load()
  File "/usr/local/lib/python3.9/dist-packages/composeparser/parse.py", line 23, in load
    return json.loads(self.lib.load(s).decode('utf-8'))
AttributeError: 'NoneType' object has no attribute 'decode'
```

or

```bash
Traceback (most recent call last):
  File "/usr/local/bin/nomadgen", line 7, in <module>
    main(args)
  File "/usr/local/lib/python3.9/dist-packages/composenomadconvertor/produce_tasks.py", line 106, in main
    result = pr.gen_nomad_job()
  File "/usr/local/lib/python3.9/dist-packages/composenomadconvertor/produce_tasks.py", line 95, in gen_nomad_job
    job_name = list(self.compose_obj['networks'].keys())[0]
KeyError: 'networks'
```` 

The last one above came from a hello world example file - nothing exotic:

```yml
version: "3"
services:
  hello:
    image: hello-world:latest
```

Do you have examples of files that the script worked with? What are potential restrictions?

**Comment by uchenic** [comment]
HI, I had to add this beforehand.
https://github.com/uchenic/compose-to-nomad/tree/master/example

**Comment by mpolinowski** [comment]
Hmm I cannot get it to run ...

1. I made sure I had the latest version installed:

```bash
pip install ComposeNomadConvertor                                                                                     
Requirement already satisfied: ComposeNomadConvertor in /usr/local/lib/python3.9/dist-packages (0.0.3)
Requirement already satisfied: ComposeParser in /usr/local/lib/python3.9/dist-packages (from ComposeNomadConvertor) (0.0.3)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.9/dist-packages (from ComposeNomadConvertor) (6.0)
``` 

2. I downloaded your example file [docker-compose.stripped.yml](https://github.com/uchenic/compose-to-nomad/blob/master/example/docker-compose.stripped.yml).

3. And ran the command:

```bash
nomadgen docker-compose.stripped.yml compose_stripped.nomad.json 

Traceback (most recent call last):
  File "/usr/local/bin/nomadgen", line 7, in <module>
    main(args)
  File "/usr/local/lib/python3.9/dist-packages/composenomadconvertor/produce_tasks.py", line 106, in main
    result = pr.gen_nomad_job()
  File "/usr/local/lib/python3.9/dist-packages/composenomadconvertor/produce_tasks.py", line 97, in gen_nomad_job
    nomad_job['job'] = dict([self.gen_job(j_n) for j_n in [job_name]])
  File "/usr/local/lib/python3.9/dist-packages/composenomadconvertor/produce_tasks.py", line 97, in <listcomp>
    nomad_job['job'] = dict([self.gen_job(j_n) for j_n in [job_name]])
  File "/usr/local/lib/python3.9/dist-packages/composenomadconvertor/produce_tasks.py", line 91, in gen_job
    job['group'] = dict([self.gen_group(g_n) for g_n in [group_name]])
  File "/usr/local/lib/python3.9/dist-packages/composenomadconvertor/produce_tasks.py", line 91, in <listcomp>
    job['group'] = dict([self.gen_group(g_n) for g_n in [group_name]])
  File "/usr/local/lib/python3.9/dist-packages/composenomadconvertor/produce_tasks.py", line 79, in gen_group
    group['task'] = self.gen_service_tasks(self.compose_obj['services'],
  File "/usr/local/lib/python3.9/dist-packages/composenomadconvertor/produce_tasks.py", line 70, in gen_service_tasks
    tasks = dict([
  File "/usr/local/lib/python3.9/dist-packages/composenomadconvertor/produce_tasks.py", line 71, in <listcomp>
    self.gen_service_task(task_name, task, group_name)
  File "/usr/local/lib/python3.9/dist-packages/composenomadconvertor/produce_tasks.py", line 24, in gen_service_task
    service.get('image', self.docker_registry + task_name),
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

Maybe a Python 3.9 issue?

**Comment by uchenic** [comment]
`pip install ComposeNomadConvertor`
```

Collecting ComposeNomadConvertor
  Using cached ComposeNomadConvertor-0.0.4-py3-none-any.whl (5.9 kB)
Collecting ComposeParser
  Using cached ComposeParser-0.0.4-py3-none-any.whl (5.5 MB)
Collecting pyyaml
  Using cached PyYAML-6.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (661 kB)
Installing collected packages: pyyaml, ComposeParser, ComposeNomadConvertor
Successfully installed ComposeNomadConvertor-0.0.4 ComposeParser-0.0.4 pyyaml-6.0
```

**Comment by mpolinowski** [comment]
Yeah!

This worked - now I have to figure out how to feed it my compose files :)
Thank you for your help and this wonderful program!
